spring:
  datasource:
    url: jdbc:h2:mem:brasilpanel
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  security:
    filter:
      order: 10

server:
  port: 8080